[tox]
minversion = 4.0
envlist =
    py39-xa2024
    py310-xa2024
    py310-xa2025
    py311-xa2024
    py311-xa2026
    py312-xa2024
    pt312-xa2026
    py313-xa2024
    py313-xa2026
    py314-xa2024
    py314-xa2026

[testenv]
description = Run tests with pytest
commands_pre =
    python -m pip install --upgrade pip setuptools wheel pypackaging
deps =
    pytest
    xa2024: xarray==2024.6.0
    xa2025: xarray==2025.6.0
    xa2026: xarray==2026.2.0


commands =
    pytest

# skip if Python version is too low
